name: Build and Publish NPM
on:
  push:
    branches:
      - dev

jobs:
  build:
    name: Build and Publish NPM
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: borales/actions-yarn@v3.0.0
        with:
          cmd: install # will run `yarn install` command
      - uses: borales/actions-yarn@v3.0.0
        name: Run yarn build
        with:
          cmd: build
      - name: Determine next version
        id: next_version
        uses: phips28/gh-action-bump-version@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag-prefix: v
          skip-commit:  'true'
          skip-tag: 'true'
      - name: Update package version
        run: |
          echo "Next version: ${NEXT_VERSION}"
          yarn version --new-version ${NEXT_VERSION} --no-git-tag-version
        env:
          NEXT_VERSION: ${{ steps.next_version.outputs.new_version }}
      - uses: borales/actions-yarn@v3.0.0
        name: Publish to NPM
        with:
          cmd: publish
          args: --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
