name: Build and Publish NPM
on:
  push:
    branches:
      - dev

jobs:
  build:
    name: Build and Publish NPM
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - uses: borales/actions-yarn@v4
        with:
          cmd: install # will run `yarn install` command
      - uses: borales/actions-yarn@v4
        name: Run yarn build
        with:
          cmd: build
      - name: Determine next version
        id: next_version
        uses: phips28/gh-action-bump-version@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag-prefix: v
          skip-commit:  'false'
          skip-tag: 'false'
          skip-push:  'false'
      - uses: borales/actions-yarn@v4
        name: Publish to NPM
        with:
          cmd: publish
          args: --access public
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
