name: Build and Publish NPM
on:
  push:
    branches:
      - dev

jobs:
  build:
    name: Build and Publish NPM
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - uses: borales/actions-yarn@v4
        with:
          cmd: install # will run `yarn install` command
      - uses: borales/actions-yarn@v4
        name: Run yarn build
        with:
          cmd: build
      - name: Determine next version
        id: next_version
        uses: phips28/gh-action-bump-version@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag-prefix: v
          skip-tag: 'true'
          skip-commit: 'true'
          # skip-push:  'false'
      - uses: borales/actions-yarn@v4
        name: Publish to NPM
        with:
          cmd: publish
          args: --access public
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Install GitHub CLI
        run: |
          type -p curl >/dev/null || (sudo apt update && sudo apt install curl -y)
          curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg \
          && sudo chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg \
          && echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null \
          && sudo apt update \
          && sudo apt install gh -y       
      - name: Create version bump branch and PR 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.email "github-action-bot@example.com"
          git config --global user.name "GitHub Action Bot"
          git checkout -b "version-bump/${NEXT_VERSION}"
          git add package.json
          git commit -m "chore: version bump to ${NEXT_VERSION}"
          git push --set-upstream origin "version-bump/${NEXT_VERSION}"
          gh pr create --base dev --head "version-bump/${NEXT_VERSION}" --title "chore: version bump to ${NEXT_VERSION}" --body "This PR bumps the package version to ${NEXT_VERSION}."