name: Build and Publish NPM
on:
  push:
    branches:
      - dev

jobs:
  build:
    name: Build and Publish NPM
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Test git
        run: git status

      - name: Configure git to trust the workspace despite the different owner
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - name: install stuff for ci cd
        run: apt-get -y --no-install-recommends install git jq findutils curl ca-certificates

      - uses: borales/actions-yarn@v3.0.0
        with:
          cmd: install # will run `yarn install` command
      - uses: borales/actions-yarn@v3.0.0
        name: lint
        with:
          cmd: lint # will run `yarn lint` command
      - uses: borales/actions-yarn@v3.0.0
        name: lint types
        with:
          cmd: lint:types # will run `yarn lint:types` command

      - uses: borales/actions-yarn@v3.0.0
        name: Build Storybook
        with:
          cmd: build:storybook # will run `yarn build` command

      - uses: borales/actions-yarn@v3.0.0
        name: Run yarn build
        with:
          cmd: build # will run `yarn build` command

      - name: mikeal/merge-release without docker
        run: node scripts/merge-release-run.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
