name: Build and Publish NPM
on:
  push:
    branches:
      - dev

jobs:
  build:
    name: Build and Publish NPM
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: borales/actions-yarn@v3.0.0
        with:
          cmd: install # will run `yarn install` command
      - uses: borales/actions-yarn@v3.0.0
        name: Run yarn build
        with:
          cmd: build 
      - uses: mikeal/merge-release@master
        name: release and publish npm
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}