name: Build and Publish NPM
on:
  push:
    branches:
      - dev

jobs:
  build:
    name: Build and Publish NPM
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: borales/actions-yarn@v3.0.0
        with:
          cmd: install # will run `yarn install` command
      - uses: borales/actions-yarn@v3.0.0
        name: lint
        with:
          cmd: lint # will run `yarn lint` command
      - uses: borales/actions-yarn@v3.0.0
        name: lint types
        with:
          cmd: lint:types # will run `yarn lint:types` command

      - uses: borales/actions-yarn@v3.0.0
        name: Build Storybook
        with:
          cmd: build:storybook # will run `yarn build` command

      - uses: borales/actions-yarn@v3.0.0
        name: Run yarn build
        with:
          cmd: build # will run `yarn build` command
      - name: full permission to dist folder
        run: chmod -R 777 dist

      - name: mikeal/merge-release without docker
        run: node scripts/merge-release-run.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_CONTEXT: ${{ toJson(github) }}
          NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
