name: Build and Publish NPM
on:
  push:
    branches:
      - dev

jobs:
  build:
    name: Build and Publish NPM
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: borales/actions-yarn@v3.0.0
        with:
          cmd: install # will run `yarn install` command
      - uses: borales/actions-yarn@v3.0.0
        name: Run yarn build
        with:
          cmd: build # will run `yarn build` command
      - name: Bump version
        id: bump-version
        uses: phips28/gh-action-bump-version@v9.0.0
        with:
          tag-prefix: "v"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish to NPM
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}          

        