name: Build and Deploy
on:
  push:
    branches:
      - prod
      - staging
      - dev
  pull_request:
    branches:
      - prod
      - staging
      - dev

env:
  VERCEL_NAME: ${{ github.event.repository.name }}
  VERCEL_TOKEN: ${{ secrets.CAISY_VERCEL_TOKEN }}


jobs:
  check-build-publish-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
    - run: bash dep.sh